export const PRESET_TEMPLATES = [
  {
    id: 'minimal',
    name: 'Minimal Clean',
    description: 'Simple and elegant design focusing on content clarity',
    icon: 'Layout',
    tags: ['Clean', 'Professional', 'Minimal'],
    data: {
      id: 'minimal',
      name: 'Minimal Clean Template',
      layout: 'single-column',
      sections: [
        {
          id: 'header',
          type: 'header',
          title: 'Your Product Title',
          subtitle: 'Compelling subtitle goes here',
          backgroundColor: '#ffffff',
          textColor: '#000000',
          editable: true,
        },
        {
          id: 'description',
          type: 'text',
          content: 'Describe your product or service here. Make it compelling and clear.',
          backgroundColor: '#f9fafb',
          editable: true,
        },
        {
          id: 'features',
          type: 'features',
          items: [
            { title: 'Feature 1', description: 'Description of feature 1' },
            { title: 'Feature 2', description: 'Description of feature 2' },
            { title: 'Feature 3', description: 'Description of feature 3' },
          ],
          layout: 'grid-3',
          editable: true,
        },
        {
          id: 'cta',
          type: 'cta',
          text: 'Get Started',
          backgroundColor: '#2563eb',
          textColor: '#ffffff',
          editable: true,
        },
      ],
      colors: {
        primary: '#2563eb',
        secondary: '#64748b',
        background: '#ffffff',
        text: '#1f2937',
      },
      fonts: {
        heading: 'Inter',
        body: 'Inter',
      },
    },
  },
  {
    id: 'modern',
    name: 'Modern Bold',
    description: 'Contemporary design with vibrant colors and dynamic layout',
    icon: 'Zap',
    tags: ['Modern', 'Bold', 'Creative'],
    data: {
      id: 'modern',
      name: 'Modern Bold Template',
      layout: 'multi-column',
      sections: [
        {
          id: 'hero',
          type: 'hero',
          title: 'Make an Impact',
          subtitle: 'Your message here',
          backgroundImage: null,
          backgroundColor: '#1f2937',
          textColor: '#ffffff',
          editable: true,
        },
        {
          id: 'highlights',
          type: 'highlights',
          items: [
            { icon: '⚡', title: 'Fast', description: 'Lightning quick performance' },
            { icon: '🎯', title: 'Targeted', description: 'Reach your audience' },
            { icon: '💡', title: 'Innovative', description: 'Cutting edge solutions' },
          ],
          layout: 'grid-3',
          editable: true,
        },
        {
          id: 'testimonials',
          type: 'testimonials',
          items: [
            { text: 'Great product!', author: 'Customer 1' },
            { text: 'Highly recommended', author: 'Customer 2' },
          ],
          editable: true,
        },
        {
          id: 'footer-cta',
          type: 'cta',
          text: 'Join Now',
          backgroundColor: '#3b82f6',
          textColor: '#ffffff',
          editable: true,
        },
      ],
      colors: {
        primary: '#3b82f6',
        secondary: '#06b6d4',
        background: '#ffffff',
        text: '#1f2937',
      },
      fonts: {
        heading: 'Poppins',
        body: 'Inter',
      },
    },
  },
  {
    id: 'elegant',
    name: 'Elegant Premium',
    description: 'Sophisticated design for luxury and premium products',
    icon: 'Palette',
    tags: ['Elegant', 'Premium', 'Luxury'],
    data: {
      id: 'elegant',
      name: 'Elegant Premium Template',
      layout: 'centered',
      sections: [
        {
          id: 'intro',
          type: 'header',
          title: 'Luxury Experience',
          subtitle: 'Crafted for excellence',
          backgroundColor: '#faf8f3',
          textColor: '#2d2d2d',
          editable: true,
        },
        {
          id: 'gallery',
          type: 'gallery',
          items: [
            { image: null, caption: 'Image 1' },
            { image: null, caption: 'Image 2' },
            { image: null, caption: 'Image 3' },
          ],
          layout: 'carousel',
          editable: true,
        },
        {
          id: 'story',
          type: 'text',
          content: 'Tell your brand story. Share your journey and values.',
          backgroundColor: '#ffffff',
          editable: true,
        },
        {
          id: 'premium-cta',
          type: 'cta',
          text: 'Discover More',
          backgroundColor: '#8b7355',
          textColor: '#ffffff',
          editable: true,
        },
      ],
      colors: {
        primary: '#8b7355',
        secondary: '#d4af37',
        background: '#faf8f3',
        text: '#2d2d2d',
      },
      fonts: {
        heading: 'Playfair Display',
        body: 'Lato',
      },
    },
  },
  {
    id: 'conversion',
    name: 'Conversion Focused',
    description: 'Optimized for maximum conversions and engagement',
    icon: 'Target',
    tags: ['Conversion', 'Sales', 'Performance'],
    data: {
      id: 'conversion',
      name: 'Conversion Focused Template',
      layout: 'funnel',
      sections: [
        {
          id: 'value-prop',
          type: 'header',
          title: 'Solve Your Problem',
          subtitle: 'Here\'s how we help',
          backgroundColor: '#ffffff',
          textColor: '#000000',
          editable: true,
        },
        {
          id: 'pain-points',
          type: 'features',
          items: [
            { title: 'Problem 1', description: 'How we solve it' },
            { title: 'Problem 2', description: 'How we solve it' },
            { title: 'Problem 3', description: 'How we solve it' },
          ],
          layout: 'list',
          editable: true,
        },
        {
          id: 'social-proof',
          type: 'stats',
          items: [
            { number: '10K+', label: 'Happy Customers' },
            { number: '99%', label: 'Satisfaction Rate' },
            { number: '24/7', label: 'Support' },
          ],
          editable: true,
        },
        {
          id: 'primary-cta',
          type: 'cta',
          text: 'Start Free Trial',
          backgroundColor: '#dc2626',
          textColor: '#ffffff',
          editable: true,
        },
      ],
      colors: {
        primary: '#dc2626',
        secondary: '#f97316',
        background: '#ffffff',
        text: '#1f2937',
      },
      fonts: {
        heading: 'Inter',
        body: 'Inter',
      },
    },
  },
];
