name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS_JSON }}
          export_default_credentials: true

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker asia-south2-docker.pkg.dev
      - name: Debug secrets
        run: |
            echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"
            echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}"


      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} \
            --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }} \
            --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} \
            --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }} \
            --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }} \
            --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }} \
            --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }} \
            --build-arg NEXT_PUBLIC_GITHUB_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GITHUB_CLIENT_ID }} \
            -t asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-marketplace/ai-marketplace-assistant:${{ github.sha }} .

      - name: Push image to Artifact Registry
        run: |
          docker push asia-south2-docker.pkg.dev/ai-markeplace-assis/ai-marketplace/ai-marketplace-assistant:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ai-marketplace-assistant \
            --image asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-marketplace/ai-marketplace-assistant:${{ github.sha }} \
            --region asia-south2 \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --quiet
